---
apiVersion: v1
kind: Namespace
metadata:
  name: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: server
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: IMAGE
          volumeMounts:
            - name: spiffe-workload-api
              mountPath: /spiffe-workload-api
              readOnly: true
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///spiffe-workload-api/agent.sock
          ports:
            - containerPort: 33333
      volumes:
        - name: spiffe-workload-api
          csi:
            driver: "csi.spiffe.io"
            readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: server
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 33333
      targetPort: 33333